version: "2"

services:
  mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_PASSWORD=123456
        - MYSQL_USER=test
    ports:
        - "3306:3306"
  redis:
    image: redis:3.2
    ports:
        - "6379:6379"
    volumes:
        - /redis:/data
  resque:
    image: ennexa/resque-web
    links:
        - redis:redisserver
    ports:
        - "5678:5678"
    command: "-r redis://redisserver:6379"
  
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mysql
      - redis
      - datadog
    environment:
      - PROTECTED_USER=me
      - PROTECTED_PASSWORD=123456
  datadog:
    image: datadog/docker-dd-agent
    environment:
        - DD_APM_ENABLED=true
        - DD_BIND_HOST=0.0.0.0
        - DD_API_KEY
    ports:
        - "8126:8126"
